#!/usr/bin/env python3
"""gen_irq_vectors.py — Generate IRQ handler stubs for x86-64 IDT vectors 32-255

Each handler stub pushes a fake error code (0) and the interrupt number (trapno),
then jumps to alltraps. This matches the TRAP_NOERR macro pattern.

Also generates irq_handler_table, an array of handler addresses for C code to reference.
"""

import sys

def main():
    out_path = sys.argv[1] if len(sys.argv) > 1 else "kernel/irq_vectors.S"

    lines = []
    lines.append("/*")
    lines.append(" * irq_vectors.S - Auto-generated IRQ handler stubs (vectors 32-255)")
    lines.append(" * Generated by gen_irq_vectors.py - DO NOT EDIT MANUALLY")
    lines.append(" */")
    lines.append("")
    lines.append(".text")
    lines.append(".globl alltraps")
    lines.append("")

    # Generate individual handler stubs
    for vec in range(32, 256):
        lines.append(f".globl handler_irq_{vec}")
        lines.append(f"handler_irq_{vec}:")
        lines.append(f"    pushq   $0              /* fake error code */")
        lines.append(f"    pushq   ${vec}           /* trapno = interrupt number */")
        lines.append(f"    jmp     alltraps")
        lines.append("")

    # Generate handler address table
    lines.append(".section .data")
    lines.append(".globl irq_handler_table")
    lines.append("irq_handler_table:")
    for vec in range(32, 256):
        lines.append(f"    .quad handler_irq_{vec}")
    lines.append("")

    with open(out_path, "w") as f:
        f.write("\n".join(lines))

    print(f"Generated {out_path} with {256-32} IRQ handler stubs")

if __name__ == "__main__":
    main()